// Client exports first (to avoid circular deps)
export { queryClient, getAuthToken } from './client'
export { QueryProvider } from './QueryProvider'

// Query hooks exports
export * from './authQuery'
export * from './projectsQuery'
export * from './servicesQuery'
export * from './serviceImagesQuery'
export * from './careersQuery'
export * from './applicationsQuery'
export * from './contactQuery'
export * from './paymentsQuery'
export * from './dashboardQuery'
export * from './favoritesQuery'
export * from './searchQuery'
export * from './healthQuery'
export * from './projectAssetsQuery'
export * from './projectImagesQuery'
export * from './projectAssignmentsQuery'
export * from './projectTiersQuery'
export * from './serviceImagesQuery'
// Re-export commonly used hooks
export { useGetCareerStats, usePublishCareer, useUnpublishCareer } from './careersQuery'
export { APPLICATION_STATUS, STATUS_WORKFLOW, STATUS_STYLE } from './applicationsQuery'